## Numpy Arrays

In [3]:
import numpy as np

#### Creating Array from List

In [5]:
arr_1D = np.array([1,2,3,4,5])
print("1D Array: ", arr_1D)

arr_2D = np.array([[1,2,3],[4,3,5]])
print("2D Array: ", arr_2D)

1D Array:  [1 2 3 4 5]
2D Array:  [[1 2 3]
 [4 3 5]]


### List vs Numpy Array

In [9]:
py_list = [1,2,3] # element wise multiplication
print("python list multiplication: ", py_list*2)

np_array = np.array([1,2,3])
print("python list multiplication: ", np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(100000)]
print("\n List operation time: ", time.time()-start)

start = time.time()
np_array = np.arange(100000)
print("\n Numpy operation time: ", time.time()-start)

python list multiplication:  [1, 2, 3, 1, 2, 3]
python list multiplication:  [2 4 6]

 List operation time:  0.19695568084716797

 Numpy operation time:  0.05748248100280762


### Creating array from scratch

In [15]:
zeros = np.zeros((3,4))
print("zeros array: \n", zeros)

ones =  np.ones((2,3))
print("ones array: \n", ones)

full = np.full((2,2),7)
print("full array: \n", full)

random = np.random.random((2,3))
print("Random array: \n", random)

sequence = np.arange(0,10,2)
print("Sequence array: \n", sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
Random array: 
 [[0.88412789 0.55140109 0.64759391]
 [0.57358458 0.10652128 0.33584401]]
Sequence array: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [17]:
vector = np.array([1,2,3])
print("Vector: \n",vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix: \n",matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor: \n",tensor)

Vector: 
 [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Properties of Array

In [25]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Array: \n", arr)
print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("Data Type: ", arr.dtype)
print("Transpose Matrix: \n", arr.T)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Dimension:  2
Size:  6
Data Type:  int64
Transpose Matrix: 
 [[1 4]
 [2 5]
 [3 6]]


### Array Reshaping

In [ ]:
arr =  np.arange(12)
print("Orginal Array: ", arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped Array: ", reshaped)

# returns copy 
flattend = reshaped.flatten()
print("\n Flattend Array: ", flattend)

# ravel (returns view means return original array, instead of copy)
raveled = reshaped.ravel()
print("\n Raveled Array: ", raveled)


Orginal Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped Array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattend Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
