## Numpy Array Operations

In [1]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing: ", arr[2:7])
print("Basic Slicing with step: ", arr[1:8:2])
print("Negative indexing: ", arr[-3])

Basic Slicing:  [3 4 5 6 7]
Basic Slicing with step:  [2 4 6 8]
Negative indexing:  8


In [7]:
arr_2D = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific Element: ", arr_2D[1,2])
print("Entire Row: ", arr_2D[1])
print("Entire Column: ", arr_2D[:, 1])

Specific Element:  6
Entire Row:  [4 5 6]
Entire Column:  [2 5 8]


### Sorting

In [11]:
unsorted_arr = np.array([3,1,5,4,2,6,9,4])
print("Sorted Array: ", np.sort(unsorted_arr))

unsorted_arr_2D = np.array([[2,5,1],
                            [3,6,4],
                            [9,5,10]])
print("Sorted 2D array by column: \n", np.sort(unsorted_arr_2D, axis=0))
print("Sorted 2D array by Row: \n", np.sort(unsorted_arr_2D, axis=1))

Sorted Array:  [1 2 3 4 4 5 6 9]
Sorted 2D array by column: 
 [[ 2  5  1]
 [ 3  5  4]
 [ 9  6 10]]
Sorted 2D array by Row: 
 [[ 1  2  5]
 [ 3  4  6]
 [ 5  9 10]]


### Filtering

In [12]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers%2 == 0]
print("Even Numbers: ", even_numbers)

Even Numbers:  [ 2  4  6  8 10]


### Filter with Mask

In [13]:
mask = numbers > 5
print("Numbers Greater than 5: ", numbers[mask])

Numbers Greater than 5:  [ 6  7  8  9 10]


### Fancy Indexing vs np.where()

In [18]:
indices =  [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("Np where: ", numbers[where_result])

[1 3 5]
Np where:  [ 6  7  8  9 10]


In [ ]:
condition_array = np.where(numbers > 5, True, False) # numbers > 5’ is a condition that returns True if it is satisfied, and False if it is not
print(condition_array)

[False False False False False  True  True  True  True  True]


### Adding and Removing Data

In [22]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined_arr = np.concatenate((arr1, arr2))
print(combined_arr)

[1 2 3 4 5 6]


### Array Compatibility

In [25]:
a = np.array([1,2,3])
b = np.array([4,5,6,7])
c = np.array([7,8,9])

print("Compatibility Shape: ", a.shape == c.shape)
print("Compatibility Shape: ", a.shape == b.shape)

Compatibility Shape:  True
Compatibility Shape:  False


In [28]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row)) # Vstack used for adding row
print("original: \n", original)
print("with new row: \n", with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original, new_col))
print("original: \n", original)
print("with new col: \n", with_new_col)

original: 
 [[1 2]
 [3 4]]
with new row: 
 [[1 2]
 [3 4]
 [5 6]]
original: 
 [[1 2]
 [3 4]]
with new col: 
 [[1 2 7]
 [3 4 8]]


In [29]:
arr =  np.array([1,2,3,4,5])
delelted = np.delete(arr, 2)
print("Array after deletion: ", delelted)

Array after deletion:  [1 2 4 5]
