In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])
print("=== Zomato sales analysis ===")
print("\nSales data Shape: ", sales_data.shape)
print("Sample data for 1st 3 resturents: \n", sales_data[:3])

=== Zomato sales analysis ===

Sales data Shape:  (5, 5)
Sample data for 1st 3 resturents: 
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [11]:
# Total sales per year
print(np.sum(sales_data, axis = 0))

yearly_total = np.sum(sales_data[:, 1:], axis = 0)
print(yearly_total)

# Minimum sales per resturents
min_sales = np.min(sales_data[:, 1:], axis=0)
print(min_sales)

# Maximum sales per year
max_sales = np.max(sales_data[:,1:],axis=0)
print(max_sales)

# Average sales per resturents
avg_sales = np.mean(sales_data[:, 1:], axis = 1)
print(avg_sales)

[     15  810000  945000 1085000 1240000]
[ 810000  945000 1085000 1240000]
[120000 140000 160000 190000]
[200000 230000 260000 300000]
[200000. 152500. 247500. 225000. 195000.]
